---- TABLA TIPO MASCOTA

CREATE TABLE CLASIFICACION (
CODIGO_CLASIFICACION int NOT NULL IDENTITY (1,1) PRIMARY KEY,
DESCRIPCION VARCHAR (30)
);


ALTER TABLE MASCOTAS
ADD CLASIFICACION int;



ALTER TABLE MASCOTAS
ADD FOREIGN KEY (CLASIFICACION) REFERENCES CLASIFICACION(CODIGO_CLASIFICACION);