USE MASCOTAS
GO 
---- CREACION DE TABLAS CON PRIMARY KEY

--- TABLA USUARIO

CREATE TABLE USUARIOS (
CODIGO_USUARIO int NOT NULL IDENTITY (1, 1) PRIMARY KEY,
USUARIO varchar(20) NOT NULL,
CLAVE varchar(20) NOT NULL,
NOMBRE_USUARIO varchar(100) NOT NULL,
CORREO varchar (50) NOT NULL,
FECHA_REGISTRO datetime NOT NULL,
CODIGO_PERFIL int NOT NULL
);  


---- TABLA PERFIL USUARIO

CREATE TABLE PERFIL (
CODIGO_PERFIL int NOT NULL IDENTITY (1,1) PRIMARY KEY,
DESCRIPCION VARCHAR (25)
);

--TABLA MASCOTAS
CREATE TABLE MASCOTAS (
CODIGO_MASCOTA int NOT NULL IDENTITY (1,1) PRIMARY KEY,
NOMBRE_MASCOTA varchar(50) NOT NULL,
RAZA varchar(50) NOT NULL,
EDAD nvarchar(5) NOT NULL,
ESTADO varchar(15) NOT NULL,
FOTO VARBINARY(MAX),
INFORMACION varchar (200),
COMENTARIOS varchar (200)
);


--- TABLA VACUNAS
CREATE TABLE VACUNAS (
CODIGO_VACUNA int NOT NULL IDENTITY (1,1) PRIMARY KEY,
NOMBRE_VACUNA varchar(100) NOT NULL,
COMENTARIOS varchar(200) 
);

---- TABLA ADMINISTRACION VACUNAS
CREATE TABLE VACUNAS_DET (
CODIGO_MVD int NOT NULL IDENTITY (1,1) PRIMARY KEY,
CODIGO_MASCOTA int NOT NULL,
CODIGO_VACUNA int NOT NULL,
FECHA_APLICACION datetime NOT NULL
);

----- TABLA CASTRACION
CREATE TABLE CASTRACION (
CODIGO_CASTRACION int NOT NULL IDENTITY (1,1) PRIMARY KEY,
CODIGO_MASCOTA int NOT NULL,
FECHA_CASTRACION datetime NOT NULL,
COMENTARIOS varchar (200)
);

--TABLA FAVORITOS
CREATE TABLE FAVORITOS (
CODIGO int NOT NULL IDENTITY (1,1) PRIMARY KEY,
CODIGO_USUARIO int NOT NULL,
CODIGO_MASCOTA int NOT NULL
);




----- TABLA ADOPCIONES_ENC
CREATE TABLE CITAS_ENC(
ID_CITA int NOT NULL IDENTITY (1,1) PRIMARY KEY,
CODIGO_USUARIO int NOT NULL,
NOMBRE_USUARIO varchar(100) NOT NULL,
DIRECCION varchar(250) NOT NULL,
TELEFONO VARCHAR(25) NOT NULL,
FECHA datetime NOT NULL,
FECHA_RECOLECCION datetime NOT NULL,
COMENTARIOS varchar(300),
ESTADO varchar(15) NOT NULL
);

---TABLA ADOPCIONES_DET
CREATE TABLE CITAS_DET(
ID_CITA int NOT NULL,
NUMERO_LINEA int NOT NULL IDENTITY (1,1) PRIMARY KEY,
CODIGO_MASCOTA int NOT NULL,
NOMBRE_MASCOTA varchar(50) NOT NULL
);

