name: Ejecutar Script

on:
    push:
        branches:
            - master

jobs:
    execute:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout de Repositorio
              uses: actions/checkout@v2

            - name: Instalar cliente de postgres
              run: sudo apt-get -y install postgresql-client

            - name: Buscar el archivo SQL
              run: |
                # Encuentra el último archivo SQL modificado o añadido
                LAST_SQL=$(git log -1 --diff-filter=AM --name-only --pretty=format: | grep ".sql$" | head -1)
                echo "Ultimo archivo SQL encontrado: $LAST_SQL"
                echo "export LAST_SQL=$LAST_SQL" >> $GITHUB_ENV

            -  name: Ejecutar el último archivo SQL
               run: |
                cat $LAST_SQL | psql "${{ secrets.POSTGRES_URL }}"