name: Ejecutar Script

on:
    push:
        branches:
            - master

jobs:
    execute:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout de Repositorio
              uses: actions/checkout@v2

            - name: Instalar cliente de postgres
              run: sudo apt-get -y install postgresql-client
            
            - name: Buscar el último archivo SQL
              id: get_sql
              run: |
                # Encuentra el último archivo SQL modificado o añadido
                LAST_SQL=$(git log -1 --diff-filter=AM --name-only --pretty=format: | grep ".sql$" | head -1)
                echo "Último archivo SQL encontrado: $LAST_SQL"
                echo "::set-output name=sql_file::$LAST_SQL"

            - name: Subir archivo SQL como artefacto
              uses: actions/upload-artifact@v2
              with:
                name: sql-script
                path: ${{ steps.get_sql.outputs.sql_file }}

            - name: Descargar archivo SQL
              uses: actions/download-artifact@v2
              with:
                name: sql-script

            -  name: Ejecutar el archivo SQL
               run: |
                cat ${{ steps.get_sql.outputs.sql_file }} | psql "${{ secrets.POSTGRES_URL }}"