name: Ejecutar Script

on:
    push:
        branches:
            - master

jobs:
    execute:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repositorio
              uses: actions/checkout@v2

            - name: Instalar PostgreSQL client
              run: sudo apt-get -y install postgresql-client

            - name: Buscar el archivo SQL
              id: get_sql
              run: |
                LAST_SQL=$(git log -1 --diff-filter=AM --name-only --pretty=format: | grep ".sql$" | head -1)
                echo "::set-output name=sql_file::$LAST_SQL"

            - name: Ejecutar el último archivo SQL
              run: psql -h ${{ secrets.POSTGRES_HOST }} -U ${{ secrets.POSTGRES_USER }} -d ${{ secrets.POSTGRES_DB }} -p ${{ secrets.POSTGRES_PORT }} -f ${{ steps.obtener_sql.outputs.archivo_sql }}
              env:
                PGPASSWORD: ${{ secrets.POSTGRES_PASSWORD }}